openapi: 3.0.0
info:
  title: DolarApi.com
  version: 1.1.0
  description: |-
    <div class="flex flex-col">

      API desarrollada en <a href="https://es.js.org?ref=dolarapi.com" target="_blank">EsJS</a> que brinda información actualizada sobre las cotizaciones del Dólar en Argentina.

      ¿Encontraste útil esta API? <strong>¡Dejá tu ⭐ en <a href="https://github.com/enzonotario/esjs-dolar-api" alt="GitHub" target="_blank">GitHub</a>!</strong>

    ## Demo
    [App.DolarApi.com](https://app.dolarapi.com)
servers:
  - url: https://dolarapi.com
    description: Producción
  - url: http://localhost:5173
    description: Local
paths:
  /v1/dolares:
    get:
      summary: Dólares
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve todas las cotizaciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolares
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares")
  /v1/dolares/oficial:
    get:
      summary: Dólar Oficial
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Dólar Oficial
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
          headers: {}
      operationId: get-dolar-oficial
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares/oficial
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares/oficial")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares/oficial")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares/oficial")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares/oficial")
  /v1/dolares/blue:
    get:
      summary: Dólar Blue
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Dólar Blue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-blue
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares/blue
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares/blue")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares/blue")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares/blue")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares/blue")
    parameters: []
  /v1/dolares/bolsa:
    get:
      summary: Dólar Bolsa
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Dólar Bolsa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-bolsa
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares/bolsa
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares/bolsa")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares/bolsa")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares/bolsa")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares/bolsa")
    parameters: []
  /v1/dolares/contadoconliqui:
    get:
      summary: Dólar Contado con Liquidación
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Dólar Contado con liquidación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-contadoconliqui
      x-sidebar-title: Dólar CCL
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares/contadoconliqui
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares/contadoconliqui")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares/contadoconliqui")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares/contadoconliqui")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares/contadoconliqui")
    parameters: []
  /v1/dolares/tarjeta:
    get:
      summary: Dólar Tarjeta
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve el valor del Dólar Tarjeta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-tarjeta
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares/tarjeta
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares/tarjeta")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares/tarjeta")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares/tarjeta")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares/tarjeta")
    parameters: []
  /v1/dolares/mayorista:
    get:
      summary: Dólar Mayorista
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Dólar Mayorista
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-mayorista
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares/mayorista
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares/mayorista")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares/mayorista")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares/mayorista")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares/mayorista")
    parameters: []
  /v1/dolares/cripto:
    get:
      summary: Dólar Cripto
      tags:
        - Cotización actual Dólares
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Dólar Cripto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-cripto
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/dolares/cripto
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/dolares/cripto")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/dolares/cripto")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/dolares/cripto")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/dolares/cripto")
    parameters: []
  /v1/estado:
    get:
      summary: Estado de la API
      tags:
        - API
      responses:
        '200':
          description: Devuelve el estado de la API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Estado'
      operationId: get-estado
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/estado
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/estado")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/estado")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/estado")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/estado")
  /v1/cotizaciones/eur:
    get:
      summary: Euro
      tags:
        - Cotización actual Monedas
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Euro
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
          headers: {}
      operationId: get-cotizacion-eur
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/cotizaciones/eur
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/cotizaciones/eur")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/cotizaciones/eur")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/cotizaciones/eur")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/cotizaciones/eur")
  /v1/cotizaciones/brl:
    get:
      summary: Real Brasileño
      tags:
        - Cotización actual Monedas
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Real Brasileño
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
          headers: {}
      operationId: get-cotizacion-brl
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/cotizaciones/brl
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/cotizaciones/brl")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/cotizaciones/brl")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/cotizaciones/brl")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/cotizaciones/brl")
  /v1/cotizaciones/clp:
    get:
      summary: Peso Chileno
      tags:
        - Cotización actual Monedas
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Peso Chileno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
          headers: {}
      operationId: get-cotizacion-clp
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/cotizaciones/clp
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/cotizaciones/clp")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/cotizaciones/clp")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/cotizaciones/clp")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/cotizaciones/clp")
  /v1/cotizaciones/uyu:
    get:
      summary: Peso Uruguayo
      tags:
        - Cotización actual Monedas
      description: ''
      responses:
        '200':
          description: Devuelve la cotización del Peso Uruguayo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
          headers: {}
      operationId: get-cotizacion-uyu
      x-code-samples:
        - lang: curl
          label: cURL
          source: curl -X GET https://dolarapi.com/v1/cotizaciones/uyu
        - lang: javascript
          label: JavaScript (fetch)
          source: |-
            fetch("https://dolarapi.com/v1/cotizaciones/uyu")
              .then(response => response.json())
              .then(data => console.log(data));
        - lang: javascript
          label: JavaScript (axios)
          source: |-
            axios.get("https://dolarapi.com/v1/cotizaciones/uyu")
              .then(response => console.log(response.data));
        - lang: python
          label: Python
          source: |-
            import requests
            response = requests.get("https://dolarapi.com/v1/cotizaciones/uyu")
            print(response.json())
        - lang: php
          label: PHP
          source: file_get_contents("https://dolarapi.com/v1/cotizaciones/uyu")
components:
  schemas:
    Cotizacion:
      title: Cotizacion
      type: object
      x-stoplight:
        id: ce96aa7960850
      x-examples:
        Example 1:
          fechaActualizacion: '2021-01-01T00:00:00.000Z'
          compra: 123.99
          venta: 132.99
          variacion: -1.54
      properties:
        compra:
          type: number
        venta:
          type: number
        variacion:
          type: number
          nullable: true
          description: Variacion porcentual respecto al cierre anterior
        casa:
          type: string
        nombre:
          type: string
        moneda:
          type: string
        fechaActualizacion:
          type: string
      required:
        - venta
        - casa
        - nombre
        - moneda
        - fechaActualizacion
    Estado:
      title: Estado
      x-stoplight:
        id: ogwpb2wxiqwqh
      type: object
      properties:
        estado:
          type: string
        aleatorio:
          type: integer
      x-examples:
        Example 1:
          estado: Disponible
          aleatorio: 1234
